### PR TITLE
ci: build-yocto: merge the check-layer job

### LINKED ISSUE #37: Check the possibility of adding interdependence for the ci jobs
We should run the jobs with some interdependence. For example the check-layer.yml should be done first than the build jobs themselves and if the first one fails, the rest will no longer be executed.
I don't know if this is possible to do, this note will be more so that I don't forget to check.

### PR DESCRIPTION
**Pull request by quaresmajose**
We should run the jobs with some interdependence.
The check-layer job should be done first than the build jobs themselves
and if the first one fails, the rest will no longer be executed.

Fixes: https://github.com/quic-yocto/meta-qcom-hwe/issues/37

### CODE REVIEW

**Comment by quaresmajose** [comment]
The last commit is to be discarded and was just to validate the PR

**Comment by quaresmajose** [comment]
> The last commit is to be discarded and was just to validate the PR

Tested and dropped

**Comment by ricardosalveti** [comment]
> We should run the jobs with some interdependence. The check-layer job should be done first than the build jobs themselves and if the first one fails, the rest will no longer be executed.

While this makes sense in theory, I'm not sure this will give us what we want here, as quite often there are check-layer issues not really related to this repo (e.g. poky or in meta-qcom), and with this change we won't be able to produce new builds until check-layer is green.

**Comment by quaresmajose** [comment]
> > We should run the jobs with some interdependence. The check-layer job should be done first than the build jobs themselves and if the first one fails, the rest will no longer be executed.
> 
> While this makes sense in theory, I'm not sure this will give us what we want here, as quite often there are check-layer issues not really related to this repo (e.g. poky or in meta-qcom), and with this change we won't be able to produce new builds until check-layer is green.

I removed the interdependence

**Comment by quaresmajose** [comment]
I also adapted the commit
```
    ci: build-yocto: merge the check-layer job
    
    Merge this two jobs since since there are dependencies between them.
    They both want to use the same references in the repositories they use
    and need the same lock step.
    
    This will also make it possible to add interdependencies if necessary
    so that there are jobs A that depend on others B.
```

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
